# Generated by Django 4.1.7 on 2023-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_hesap_tarih_alter_post_olusturan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='tarih',
            field=models.IntegerField(null=True),
        ),
    ]
