# Generated by Django 4.1.7 on 2023-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_hesap_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='tarih',
            field=models.TextField(null=True),
        ),
    ]
